# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '@bazbt3'
tagline:          '…a simple blog by a simple man.'
description:      'Simple* man with a wonderful wife, 2 daughters. Alpha male to Loki cat, food provider to Mollie cat, poop scooper to Ruby dog. Asks silly questions. <br> <br> *Likes footnotes.'

url:              http://bazbt3.github.io
baseurl:          /

author:
  name:           'Barrie Turner'
  url:            https://app.net/bazbt3

paginate:         5
