# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            '@bazbt3'
tagline:          '…a simple blog by a simple man.'
description:      '…a simple blog by a simple man.'

name:             '@bazbt3'
url:               http://bazbt3.github.io
baseurl:          /

author:
  name:           'Barrie Turner'
  url:            https://app.net/bazbt3

paginate:         5

# Use the following plug-ins
gems:
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem.