# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '@bazbt3'
tagline:          '…a simple blog by a simple man.'
description:      'A simple* man with a wonderful wife, 2 daughters… see the About page for more. <br> <br> *Likes footnotes.'

url:              http://bazbt3.github.io
baseurl:          /

author:
  name:           'Barrie Turner'
  url:            https://app.net/bazbt3

paginate:         5
