# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            '@bazbt3'
tagline:          '…a blog born of despair & Schadenfreude. ;)'
description:      '…a blog born of despair & Schadenfreude. ;)'

name:             '@bazbt3'
url:               http://bazbt3.github.io
baseurl:          /

author:
  name:           'Barrie Turner'
  url:            https://app.net/bazbt3

paginate:         5

# Use the following plug-ins:
gems:
  - jekyll-paginate # The official Jekyll paginator.
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem.

# Mess about with this line to force updates!
