# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            '@bazbt3'
tagline:          '…a simple blog by a simple man.'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://bazbt3.github.io
baseurl:          /

author:
  name:           'Barrie Turner'
  url:            https://app.net/bazbt3

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/bazbt3/bazbt3.github.io
